### ISSUE TITLE
Use an interrupt to tell the main proc when the wget has finished

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/TrackerBox2#1]
The way I've done it now, the wget process could finish, some other process gets the same pid, and my program waits forever.

**Comment by ounsworth** [comment]
I played with waitpid a bit, to no avail.

This seems to be working, I havn't seen a crash yet. I read that the linux kernel waits some amount of time before recycling a pid for exactly this reason, so it's probably fine.

**Comment by Lockscout** [comment]
mike, off topic but, where are you? we are wondering...

-Ethan
