### ISSUE TITLE
Change math / corner detection in c++

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/TrackerBox2#6]
Create a box out of the outer corners of the two targets together.

**Comment by Lockscout** [comment]
What file would the math and the corner detection be under?

**Comment by Lockscout** [comment]
vision_utils.cpp

**Comment by Lockscout** [comment]
We can erode away the extra targets when we are in the position to use the vision. so we can make the program Find the 2 most complete targets and assume that they are 1

**Comment by Lockscout** [comment]
And then It would also erode out any other targets it sees like the other teams boiler target since it would be too small from the distance or too high up. Just a note

**Comment by ounsworth** [comment]
Thanks for putting your notes into the ticket @TMSD !

Alright, next meeting I can help you play with changing up the opencv filters.
