### ISSUE TITLE
Add a data version code to the data we send over the network

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/TrackerBox2#9]
Since we are changing the data that's being sent, we should include a version code in the data to help people diagnose the problem if they are using a Pi that has not been updated.

The RoboRIO code should print something like:

"Data Version Error: I was expecting data version code "2017", but the Pi sent data with version "2016"."

- [x] Add a `#define DATA_VERSION_CODE` to `network tracker/vision_data.h`
- [x] Add a `public static final String DATA_VERSION_CODE` to `JavaWrapper/TrackerBox2.java`
- [x] Check for this string in the incoming message in `JavaWrapper/TrackerBox2.java`
- [ ] Include this in the string that's being sent by the Pi in `network tracker/networkTracker.cpp`
- [ ] Check for this string in the incoming message in `cpp wrapper/trackerbox_client.cpp`

**Comment by BookSmart123** [comment]
still need to update pi code to send version code (verCode)
